set gdefault
set encoding=utf-8 nobomb

" Respect modeline in files
set modeline
set modelines=4
set number
syntax on
set tabstop=4
set hlsearch
set ignorecase
set incsearch
set noerrorbells
set scrolloff=3
set ruler
